apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "uyuni-suite.fullname" . }}-noti"
  labels:
    {{- include "uyuni-suite.labels" . | nindent 4 }}
spec:
  {{- if not .Values.uyuni.noti.autoscaling.enabled }}
  replicas: {{ .Values.uyuni.noti.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: uyuni-suite-noti
  template:
    metadata:
      {{- with .Values.uyuni.noti.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: uyuni-suite-noti
    spec:
      {{- with .Values.uyuni.noti.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uyuni-suite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.uyuni.noti.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.uyuni.noti.securityContext | nindent 12 }}
          image: "{{ .Values.uyuni.noti.image.repository }}:{{ .Values.uyuni.noti.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.uyuni.noti.image.pullPolicy }}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS
            value: kafka-cp-kafka.kafka.svc:9092
          - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS
            value: kafka-cp-kafka.kafka.svc:9092
          {{- if .Values.uyuni.noti.env }}
          {{- include "uyuni-suite.tplvalues.render" (dict "value" .Values.uyuni.noti.env "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - name: tomcat
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.uyuni.noti.resources | nindent 12 }}
      {{- with .Values.uyuni.noti.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uyuni.noti.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uyuni.noti.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
