{{- $fullName := include "uyuni-suite.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
data:
  nginx.conf: |-
    upstream uyuni-manager-core {
        server {{ $fullName }}-core:8080;
    }

    upstream uyuni-manager-noti {
        server {{ $fullName }}-noti:8080;
    }

    upstream uyuni-manager-batch {
        server {{ $fullName }}-batch:8080;
    }

    server {
        client_max_body_size 0;
        listen 80;
        location / {
            root    /app/build;
            index   index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/v1/monitor {
            proxy_pass  http://uyuni-manager-core/api/v1/monitor;
        }

        location /api/v1/manager {
            proxy_pass  http://uyuni-manager-core/api/v1/manager;
        }

        location /api/v1/noti {
            proxy_pass  http://uyuni-manager-noti/api/v1/noti;
        }

        location /manager/ws {
            proxy_pass  http://uyuni-manager-core/manager/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /docs {
            proxy_pass  http://uyuni-manager-core/docs;
        }
    }