{{- if .Values.uyuni.common.ingress.enabled -}}
{{- $fullName := include "uyuni-suite.fullname" . -}}
{{- if and .Values.uyuni.common.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.uyuni.common.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.uyuni.common.ingress.annotations "kubernetes.io/ingress.class" .Values.uyuni.common.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "uyuni-suite.labels" . | nindent 4 }}
  {{- with .Values.uyuni.common.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.uyuni.common.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.uyuni.common.ingress.className }}
  {{- end }}
  {{- if .Values.uyuni.common.ingress.tls }}
  tls:
    {{- range .Values.uyuni.common.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.uyuni.common.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: "/api/v1/monitor"
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-core"
                port:
                  number: 8080
          - path: "/api/v1/manager"
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-core"
                port:
                  number: 8080
          - path: "/api/v1/noti"
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-noti"
                port:
                  number: 8080
          - path: "/manager/ws"
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-core"
                port:
                  number: 8080
          - path: "/docs"
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-core"
                port:
                  number: 8080
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-frontend"
                port:
                  number: 80
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .backend.service.port.number }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
