apiVersion: v1
kind: Service
metadata:
  name: "{{ include "uyuni-suite.fullname" . }}-batch"
  labels:
    {{- include "uyuni-suite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.uyuni.batch.service.type }}
  ports:
    - port: {{ .Values.uyuni.batch.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: uyuni-suite-batch
